#!/bin/bash

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

set -e

freshshell_install_or_upgrade() {
  if [ ! -d "$HOME/.fresh" ]; then
    FRESH_LOCAL_SOURCE=https://github.com/phoolish/dotphiles.git bash <(curl -sL https://get.freshshell.com)
    if [ -f "$HOME/.dotfiles/freshrc" ]; then
      ln -sf "$HOME/.dotfiles/freshrc" "$HOME/.freshrc"
    fi
  fi
  source "$HOME/.fresh/build/shell.sh"
  fresh install
}

if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
   test -d "${xpath}" && test -x "${xpath}" ; then
  echo "xcode installed correctly"
else
  xcode-select --install
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  #append_to_zshrc '# recommended by brew doctor'

  # shellcheck disable=SC2016
  #append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

  export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulas ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151

brew bundle install --no-lock

freshshell_install_or_upgrade

fancy_echo "Manual Install:"

site_list=(
  airmailapp.com
  wunderlist.com
  docker.com
  keybase.io
)
for site in ${site_list[@]}; do
  fancy_echo "http://$i/"
done

# Verify
# brew doctor
