#!/bin/sh

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

set -e

freshshell_install_or_upgrade() {
  if [ ! -d "$HOME/.fresh" ]; then
    FRESH_LOCAL_SOURCE=https://github.com/phoolish/dotphiles.git bash <(curl -sL https://get.freshshell.com)
    if [ -f "$HOME/.dotfiles/freshrc" ]; then
      ln -sf "$HOME/.dotfiles/freshrc" "$HOME/.freshrc"
    fi
  fi
  source "$HOME/.fresh/build/shell.sh"
  fresh install
}

if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
   test -d "${xpath}" && test -x "${xpath}" ; then
  echo "xcode installed correctly"
else
  xcode-select --install
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  #append_to_zshrc '# recommended by brew doctor'

  # shellcheck disable=SC2016
  #append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

  export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulas ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151

brew bundle --file=- <<EOF
brew "git"
brew "keychain"
brew "mnr"
brew "bash-completion"
brew "the_silver_searcher"
brew "vim"
tap "neovim/neovim"
brew "neovim"
brew "ctags"
brew "wget"
brew "mosh"
brew "jq"
brew "kube-ps1"
# brew "kubectx"
brew "coreutils"

#brew "imagemagick"

# brew "openssl"
# brew unlink openssl && brew link openssl --force

#brew "libyaml"
#brew "python"
#brew "mysql"
#brew "postgresql"
#brew "mongodb"

#brew "mr"
brew "awscli"
#brew "nvm"
brew "asdf"

# tap "caskroom/versions"

#cask "dropbox"
#cask "google-chrome"
#cask "firefox"
cask "evernote"
#cask "shiftit"
#cask "rowanj-gitx"
#cask "diffmerge"
#cask "screenhero"
# cask "flux"
#cask "dragondisk"
#cask "virtualbox"
#cask "vagrant"
#cask "terraform"
#cask "arq"
#cask "cyberduck"
#cask "adium"
cask "fantastical"
cask "slack"
cask "harvest"
#cask "github-desktop"
cask "gas-mask"
cask "tunnelblick"
cask "vlc"
cask "sequel-pro"
cask "tripmode"
cask "iterm2"
cask "whatsapp"
cask "spotify"

brew "tree"
#brew "graphviz"

# Install Docker
cask "docker"
brew "docker-completion"

# install not working
#brew reinstall asciidoc --with-docbook-xsl
#export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
#brew "lastpass-cli" "--with-pinentry"
#brew "bash-git-prompt"

#brew "tmux"

#brew "ansible"

# tmux workspace manager
# http://tmuxp.readthedocs.io/en/latest/index.html
#pip install tmuxp -U

# Allows tmux access to system clipboard
#brew "reattach-to-user-namespace"

# GO
#brew "go" 

EOF

freshshell_install_or_upgrade

fancy_echo "Manual Install:"

site_list=(
  airmailapp.com
  wunderlist.com
  docker.com
  keybase.io
)
for site in ${site_list[@]}; do
  fancy_echo "http://$i/"
done

# Verify
# brew doctor
