# Get the aliases and functions

if [[ "$(uname)" == "Darwin" ]]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile"


command -v keychain  >/dev/null 2>&1 && eval $(keychain --eval --quiet --confhost)
# http://unix.stackexchange.com/a/90869
# Add ssh keys on login
#if [ -z "$SSH_AUTH_SOCK" ] ; then
#  eval `ssh-agent -s`
#  ssh-add
#fi
